workflow_details:
  name: "Example Workflow"
  description: "An example workflow for testing purposes."
time_range:
  since: "2015-01-01T00:00:00Z"
  until: "2015-02-28T23:59:59Z"
gee_project_name:
  data_source:
    name: ecoscope_poc
roi:
  config:
    file_path: "~/Downloads/Mount_Kenya_Fores.parquet"
    name_column: "FOREST"
