# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Deforestation
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Connect to Earth Engine

# %%
# parameters

gee_project_name_params = dict(
    data_source=...,
)

# %%
# call the task


gee_project_name = (
    set_gee_connection.set_task_instance_id("gee_project_name")
    .handle_errors()
    .with_tracing()
    .partial(**gee_project_name_params)
    .call()
)


# %% [markdown]
# ## Define Base Maps

# %%
# parameters

base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


base_maps = (
    set_base_maps_pydeck.set_task_instance_id("base_maps")
    .handle_errors()
    .with_tracing()
    .partial(**base_maps_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Load Region of Interest

# %%
# parameters

roi_params = dict(
    config=...,
)

# %%
# call the task


roi = (
    load_spatial_features_group.set_task_instance_id("roi")
    .handle_errors()
    .with_tracing()
    .partial(**roi_params)
    .call()
)


# %% [markdown]
# ## Extract Forest Cover Trends

# %%
# parameters

forest_cover_trends_params = dict(
    tree_cover_threshold=...,
    scale=...,
    max_pixels=...,
)

# %%
# call the task


forest_cover_trends = (
    extract_forest_cover_trends.set_task_instance_id("forest_cover_trends")
    .handle_errors()
    .with_tracing()
    .partial(client=gee_project_name, aoi=roi, **forest_cover_trends_params)
    .call()
)


# %% [markdown]
# ## Fit GAMM Model

# %%
# parameters

gamm_model_params = dict(
    degree_of_freedom=...,
    degree=...,
    family=...,
)

# %%
# call the task


gamm_model = (
    fit_gamm_model.set_task_instance_id("gamm_model")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=forest_cover_trends,
        time_column="year",
        value_column="survival_area",
        alpha=None,
        metric="aic",
        optimize_alpha=True,
        lower_bound=None,
        upper_bound=None,
        **gamm_model_params,
    )
    .call()
)


# %% [markdown]
# ## Generate Trend Predictions

# %%
# parameters

trend_predictions_params = dict()

# %%
# call the task


trend_predictions = (
    predict_gamm_trends.set_task_instance_id("trend_predictions")
    .handle_errors()
    .with_tracing()
    .partial(
        model_params=gamm_model,
        time_values=None,
        include_ci=True,
        **trend_predictions_params,
    )
    .call()
)


# %% [markdown]
# ## Create Forest Cover Trend Chart

# %%
# parameters

forest_conver_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


forest_conver_chart = (
    draw_historic_timeseries.set_task_instance_id("forest_conver_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=trend_predictions,
        current_value_column="y",
        time_column="time",
        current_value_title="Observed Survival Area",
        historic_min_column="ci_lower",
        historic_max_column="ci_upper",
        historic_mean_column="predicted",
        historic_mean_title="GAM Mean",
        historic_band_title="GAM 95% CI",
        layout_style={
            "title": "Forest survival area trend (GAM)",
            "xaxis": {"title": "Year"},
            "yaxis": {"title": "Survival Area (acres)"},
        },
        upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
        historic_mean_style=None,
        current_value_style=None,
        **forest_conver_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Forest Cover Trend Chart as Text

# %%
# parameters

persist_forest_cover_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_forest_cover = (
    persist_text.set_task_instance_id("persist_forest_cover")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=forest_conver_chart,
        **persist_forest_cover_params,
    )
    .call()
)


# %% [markdown]
# ## Create Forest Cover Trend Chart Widget

# %%
# parameters

forest_cover_widget_params = dict(
    view=...,
)

# %%
# call the task


forest_cover_widget = (
    create_plot_widget_single_view.set_task_instance_id("forest_cover_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Forest Cover Trend Chart",
        data=persist_forest_cover,
        **forest_cover_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Deforestation Dashboard

# %%
# parameters

gamm_dashboard_params = dict(
    groupers=...,
    warning=...,
)

# %%
# call the task


gamm_dashboard = (
    gather_dashboard.set_task_instance_id("gamm_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        time_range=time_range,
        widgets=[forest_cover_widget],
        **gamm_dashboard_params,
    )
    .call()
)
