# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)

load_spatial_features_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "gee_project_name": [],
        "base_maps": [],
        "time_range": [],
        "roi": [],
        "forest_cover_trends": ["gee_project_name", "roi"],
        "gamm_model": ["forest_cover_trends"],
        "trend_predictions": ["gamm_model"],
        "forest_conver_chart": ["trend_predictions"],
        "persist_forest_cover": ["forest_conver_chart"],
        "forest_cover_widget": ["persist_forest_cover"],
        "gamm_dashboard": ["workflow_details", "time_range", "forest_cover_widget"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "gee_project_name": Node(
            async_task=set_gee_connection.validate()
            .set_task_instance_id("gee_project_name")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("gee_project_name") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "roi": Node(
            async_task=load_spatial_features_group.validate()
            .set_task_instance_id("roi")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("roi") or {}),
            method="call",
        ),
        "forest_cover_trends": Node(
            async_task=extract_forest_cover_trends.validate()
            .set_task_instance_id("forest_cover_trends")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_project_name"),
                "aoi": DependsOn("roi"),
            }
            | (params_dict.get("forest_cover_trends") or {}),
            method="call",
        ),
        "gamm_model": Node(
            async_task=fit_gamm_model.validate()
            .set_task_instance_id("gamm_model")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("forest_cover_trends"),
                "time_column": "year",
                "value_column": "survival_area",
                "alpha": None,
                "metric": "aic",
                "optimize_alpha": True,
                "lower_bound": None,
                "upper_bound": None,
            }
            | (params_dict.get("gamm_model") or {}),
            method="call",
        ),
        "trend_predictions": Node(
            async_task=predict_gamm_trends.validate()
            .set_task_instance_id("trend_predictions")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "model_params": DependsOn("gamm_model"),
                "time_values": None,
                "include_ci": True,
            }
            | (params_dict.get("trend_predictions") or {}),
            method="call",
        ),
        "forest_conver_chart": Node(
            async_task=draw_historic_timeseries.validate()
            .set_task_instance_id("forest_conver_chart")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("trend_predictions"),
                "current_value_column": "y",
                "time_column": "time",
                "current_value_title": "Observed Survival Area",
                "historic_min_column": "ci_lower",
                "historic_max_column": "ci_upper",
                "historic_mean_column": "predicted",
                "historic_mean_title": "GAM Mean",
                "historic_band_title": "GAM 95% CI",
                "layout_style": {
                    "title": "Forest survival area trend (GAM)",
                    "xaxis": {
                        "title": "Year",
                    },
                    "yaxis": {
                        "title": "Survival Area (acres)",
                    },
                },
                "upper_lower_band_style": {
                    "mode": "lines",
                    "line": {
                        "color": "green",
                    },
                },
                "historic_mean_style": None,
                "current_value_style": None,
            }
            | (params_dict.get("forest_conver_chart") or {}),
            method="call",
        ),
        "persist_forest_cover": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_forest_cover")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("forest_conver_chart"),
            }
            | (params_dict.get("persist_forest_cover") or {}),
            method="call",
        ),
        "forest_cover_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("forest_cover_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Forest Cover Trend Chart",
                "data": DependsOn("persist_forest_cover"),
            }
            | (params_dict.get("forest_cover_widget") or {}),
            method="call",
        ),
        "gamm_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("gamm_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "widgets": [
                    DependsOn("forest_cover_widget"),
                ],
            }
            | (params_dict.get("gamm_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
